name: 'Redact.md'
description: 'A Github Action used by the deep state to redact data from markdown files.'
author: 'mudlabs'
branding:
  icon: scissors
  color: black
inputs:
  secrets:
    required: true
    description: 'The secrets to redact. Can be a keywords/phases list, a RegExp, or an API endpoint.'
  redact-all:
    required: false
    default: false
    description: 'Should the entire repo be scanned and redacted.'
runs:
  using: 'node12'
  main: 'index.js'

