name: 'Redacted'
description: 'A Github Action used heavily by the CIA, NSA, MI5, etc.. to automatically redact _super dupa top secret_ data from markdown files, befor **"the enemy"** can get their hands on it.'
inputs:
  secrets:
    required: true
    description: 'A list of keywords/phases to match in markdown files for redaction'
branding:
  icon: redact
  color: black
