name: 'Redact.md'
description: 'A Github Action used to redact data from markdown files.'
inputs:
  secrets:
    required: true
    description: 'A list of keywords/phases to match in markdown files for redaction'
branding:
  icon: scissors
  color: black
