name: 'Redact.md'
description: 'A Github Action used by the deep state to redact data from markdown files.'
author: 'mudlabs'
branding:
  icon: scissors
  color: black
inputs:
  symbole:
    required: false
    description: 'A string to replace all keywords/phases with. "classic" and "whiteout" are reserved words.'
    default: 'classic'
  api-endpoit:
    required: false
    description: 'A url endpoint that returns a JSON list of keywords/phases to redact.'
  comma-list:
    required: false
    description: 'A comma seperated string of keywords/phases to redact.'
  regexp:
    required: false
    description: 'A string that can be converted to a RegExp to match keywords/phases for redaction.'
  redact-all:
    required: false
    default: false
    description: 'Should the entire repo be scanned and redacted. Default behaviour is to only scan .md files in this commit.'
  glob:
    required: false
    default: '**/*.md'
    description: 'Further specifies what markdown files should be selected for redaction.'
runs:
  using: 'node12'
  main: 'index.js'

